### PR TITLE
New website

### PR DESCRIPTION
**Pull request by terhechte**
With a final, sad, goodbye, the website updated to reflect the change in hosts. Also, I tried to improve that ugly thing.

Screen Shot 2021-02-23 at 08 28 29

### CODE REVIEW

**Comment by BasThomas** [comment]
😍

**Comment by BasThomas** [comment]
Does the css also support a dark mode, actually? 😀

**Comment by terhechte** [comment]
@BasThomas Yes, dark mode is in as well :)

**Comment by terhechte** [comment]
Screen Shot 2021-02-23 at 14 29 22

**Pull request merged**
